# ImagePolicy - Defines which image tags to use (semver policy)
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: ">=6.0.0" # Accept any version 6.0.0 or higher
  filterTags:
    pattern: '^6\.[0-9]+\.[0-9]+$' # Only match 6.x.x versions
    extract: "$1"
